default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: alexander
  password: <%= ENV['DATABASE_PASSWORD'] %>

development:
  <<: *default
  database: emptiness_diary_development

test:
  <<: *default
  database: emptiness_diary_test
  username: alexander
  password: <%= ENV['DATABASE_PASSWORD'] %>

production:
  <<: *default
  database: emptiness_diary_production
  username: alexander
  password: <%= ENV['DATABASE_PASSWORD'] %>